### ISSUE TITLE
Ignore wrangler.toml in source control

### ISSUE THREAD

**Issue by zeke** [discord/avatar-remix-bot#7]
@typpo what do you think about renaming `wrangler.toml`  to `wrangler.toml.example` and git-ignoring `wrangler.toml`, so folks can make changes to the file without having to worry about committing secrets?

**Comment by JustinBeckwith** [comment]
So the good news here is that I don't think anything in `wrangler.toml` has secrets.  `DISCORD_PUBLIC_KEY` and `DISCORD_APPLICATION_ID` are publicly available.  `DISCORD_BOT_TOKEN` and `REPLICATE_API_TOKEN` are stored as secrets with wrangler.  That having been said ... it may be worth putting `<placeholder>` values anywhere we know folks will want to edit.  Do you still think we need to do a file rename here, or should we just add some of those placeholder values to make it more obvious what users need to change?

**Comment by zeke** [comment]
Good to know that secrets will not be in the file. 👍🏼 

Placeholder values would be an improvement, but I guess my thinking is that everyone who uses this project will have to change that file, and then if they ever want to make contributions to this canonical repo, they'll need to explicitly ignore those changes when doing a git commit. Not the end of the world, but maybe a bit inconvenient.

**Comment by zeke** [comment]
Nice!
